Repository nrfta/go-config, pull requests merged in 2019-06, with the labels that each got.

#1 Initial Implementation
  .editorconfig
  .github/main.workflow
  .github/release-drafter.yml
  .gitignore
  .travis.yml
  LICENSE.md
  README.md
  config.go
  go.mod
  go.sum
  tests/unit/config_test.go
  tests/unit/config_test.json
  tests/unit/unit_suite_test.go
Labels: Type: Feature

#3 migrated to go-errors
  config.go
  go.mod
  go.sum
  tests/unit/config_test.go
  tests/unit/config_test.json
Labels: Type: Enhancement

#4 Clean up readme examples and tests
  README.md
  config.go
  tests/unit/config_test.go
  tests/unit/config_test.json
Labels: Type: Documentation
